### PR TITLE
clean-up

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by danielpassos** [comment]
@corinnekrych Is it still valid? If so can you rebase that to see if it fix the build problem

**Comment by jcesarmobile** [comment]
@danielpassos I don't think so, master has CocoaPods support now, so I don't think we need the cocoapods branch anymore

**Comment by danielpassos** [comment]
@jcesarmobile Should we close it and delete the `CocoaPods` branch?

**Comment by jcesarmobile** [comment]
@corinnekrych WDYT?

**Comment by corinnekrych** [comment]
+1 close it and delete CocoaPods branch
@jcesarmobile @danielpassos

**Pull request closed without merging**
